version: 2.1

jobs:
  build:
    docker: 
      - image: cimg/node:15.1
    steps:
      - run: echo build
  deploy:
    docker: 
      - image: cimg/node:15.1
    steps:
      - run: echo deploy

workflows:
  build_QA:
    jobs:
      - build
      - hold-deploy
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold-deploy