# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  # Sample build task
  build:
    docker:
      - image: cimg/node:15.1
    parameters: # parameters are at the job level
      env:
        type: string
        default: "qa"
    working_directory: ~/project
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run: npm test
      - run:
          name: current environment check
          command: echo << parameters.envv >>
      - persist_to_workspace:
          root: ~/project
          paths:
          - "*"
  deploy:
    docker:
      - image: cimg/node:15.1
    parameters: # parameters are at the job level
      env:
        type: string
        default: "qa"
    steps:
      - attach_workspace:
          at: .
      - run: npm install surge
      - run: ls -l
      - run: ~/project/node_modules/surge/lib/cli.js --project ~/project/build --domain testCI.surge.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          envv: 'ttt'
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: staging
