version: 2.1

jobs:
  build:
    docker: 
      - image: cimg/node:15.1
    parameters:
      env: 
        type: string
    steps:
      - run: echo build
  deploy:
    docker: 
      - image: cimg/node:15.1
    parameters:
      env: 
        type: string
    steps:
      - run: echo deploy << parameters.env >>

workflows:
  build_QA:
    jobs:
      - build:
          env: QA
      - hold-deploy:
          type: approval
          requires:
            - build
      - deploy:
          env: QA
          requires:
            - hold-deploy