# version: 2.1

# orbs:
#   aws-s3: circleci/aws-s3@3.0.0
  
# jobs:
#   quality_checks:
#     docker: 
#       - image: cimg/node:15.1
#     steps:
#       - run: echo in quality checks
#   build:
#     docker: 
#       - image: cimg/node:15.1
#     working_directory: ~/project
#     parameters:
#       env: 
#         type: string
#     steps:
#       - run: echo build > build.txt
#       - persist_to_workspace:
#           root: ~/project
#           paths:
#             - '*'
#   deploy:
#     docker: 
#       - image: cimg/node:15.1
#     parameters:
#       env: 
#         type: string
#     steps:
#       - attach_workspace:
#           at: .
#       - run: 
#           name: deploy build
#           command: |
#             echo deploy << parameters.env >>
#             cat build.txt

# workflows:
#   build_QA:
#     jobs:
#       - quality_checks
#       - build:
#           env: QA
#           requires:
#             - quality_checks
#           filters:
#            branches: 
#              only: 
#               - master
#               - staging
#       - hold-deploy:
#           type: approval
#           requires:
#             - build
#       - deploy:
#           env: QA
#           filters:
#             branches:
#               only: 
#                 - master
#                 - staging
#           requires:
#             - hold-deploy





# version: 2.1

# jobs:
#   build:
#     docker:
#       - image: cimg/node:15.1
#     working_directory: ~/repo
#     parameters: 
#       env:
#         type: string
#     steps:
#       - run: echo build
#       - persist_to_workspace:
#           root: ~/repo
#           paths: /.*/   # ~/home/circleci/repo
#   deploy:
#       docker:
#         - image: cimg/node:15.1
#       steps:
#         - attach_workspace:
#             at: .
#         - run: echo in deploy job
        
# workflows:
#   build_testAndDeploy:
#     jobs:
#       - build:
#           env: QA
#       - hold_for_approval:
#           type: approval
#           requires: 
#             - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only:
#                 - master
#             tags:
#               ignore: /.*/


version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.1
    working_directory: ~/project # ~/ refers to /home/circleci
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: cp build/index.html build/200.html
      - persist_to_workspace:
          root: ~/project
          paths: "build"
  deploy-feature-review:
    docker:
      - image: cimg/node:15.1
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: Install surge and deploy to surge
          command: |
            npm install surge
            ~/project/node_modules/.bin/surge --project build/ --domain ci-01-demo.sh

workflows:
  build_deploy_review:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: 
                - /^feature/review/.*/
      - deploy-approval:
          type: approval
          requires: 
            - build
          branches:
            ignore: /.*/
          tags:
            only: 
              - /^feature/review/.*/          
      - deploy-feature-review:
          requires: 
            - deploy-approval
          filters:
            branches:
              ignore: 
                - /.*/
            tags:
              only: 
                - /^feature/review/.*/
    
