version: 2.1

jobs:
  hello:
    parameters:
      env:
        type: string
    docker:
      - image: circleci/clojure:lein-2.9.1
    steps:
      - run: echo hi from << parameters.env >>

workflows:
  version: 2
  ci-and-deploy:
    jobs:
      - hello:
          name: hello-ci
          env: ci