version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0
  
jobs:
  quality_checks:
    docker: 
      - image: cimg/node:15.1
    steps:
      run: echo in quality checks
  build:
    docker: 
      - image: cimg/node:15.1
    working_directory: ~/project
    parameters:
      env: 
        type: string
    steps:
      - run: echo build > build.txt
      - persist_to_workspace:
          root: ~/project
          paths:
            - '*'
  deploy:
    docker: 
      - image: cimg/node:15.1
    parameters:
      env: 
        type: string
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: deploy build
          command: |
            echo deploy << parameters.env >>
            cat build.txt

workflows:
  build_QA:
    jobs:
      - quality_checks
      - build:
          env: QA
          requires:
            - quality_checks
          filters:
            branches:
              - master
              - staging
      - hold-deploy:
          type: approval
          requires:
            - build
      - deploy:
          env: QA
          branches:
            - master
            - staging
          requires:
            - hold-deploy