version: 2.1

jobs:
  build:
    docker: 
      - image: cimg/node:15.1
    working_directory: ~/project
    parameters:
      env: 
        type: string
    steps:
      - run: echo build > build.txt
      - persist_to_workspace:
          root: ~/project
          paths:
            - '*'
  deploy:
    docker: 
      - image: cimg/node:15.1
    parameters:
      env: 
        type: string
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: deploy build
          command: |
            echo deploy << parameters.env >>
            cat build.txt

workflows:
  build_QA:
    jobs:
      - build:
          env: QA
      - hold-deploy:
          type: approval
          requires:
            - build
      - deploy:
          env: QA
          requires:
            - hold-deploy